#!/bin/sh
# File generated by ocamlbuild

cd '/home/mayank/Desktop/COL226-PL-Assignment/Assignment 3/A3Start'

rm -f a2.ml
# Also clean the script itself
rm -f '/home/mayank/Desktop/COL226-PL-Assignment/Assignment 3/A3Start/_build/sanitize.sh'
